name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclencher le pipeline lors d'un push sur la branche main
  pull_request:
    branches:
      - main  # Déclencher le pipeline lors d'une pull request sur la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest  # Exécuter les tests unitaires (si vous en avez)

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Attendre que le job "test" soit terminé
    if: github.ref == 'refs/heads/main'  # Déployer uniquement sur la branche main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "test-mind-launch-ai"  # Remplacez par le nom de votre application Azure
          slot-name: "production"    # Optionnel : spécifiez un slot de déploiement
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Utiliser un secret GitHub
