name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclencher le pipeline lors d'un push sur la branche main
  pull_request:
    branches:
      - main  # Déclencher le pipeline lors d'une pull request sur la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Attendre que le job "test" soit terminé
    if: github.ref == 'refs/heads/main'  # Déployer uniquement sur la branche main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
